permalink: /:year/:month/:day/:title.html


exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

highlighter: rouge
auto: true
baseurl:

gems: [jekyll-paginate]
paginate: 15
paginate_path: "blog/page:num"


destination: ./._site
plugins_dir: ./_plugins
markdown:  kramdown

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  syntax_highlighter_opts:
    wrap: div
    line_numbers: inline
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: style

redcloth:
  hard_breaks: true

production_url : https://www.cachecha.com/web-m3u8
short_name : midoks

tagline: M3U8在线解析 - M3U8在线播放器,M3U8播放器,M3U8在线,M3U8在线播放,M3U8直播源,M3U8
index_path : /index.html
about_path : /about.html

#基本参数
title: midoks
def_player_addr: https://sod.malleter.com/20211112/L57EDNF2/index.m3u8
res_url : https://www.cachecha.com/resources
categories: [test, sample]
author :
  name : midoks
  email : midoks@163.com
  github : midoks@github.com
  feedburner : feedname
  keywords : M3U8在线播放器,M3U8播放器,M3U8在线,M3U8在线播放,M3U8直播源,M3U8
  description: M3U8在线播放器,M3U8播放器,M3U8在线,M3U8在线播放,M3U8直播源,M3U8
